### ISSUE TITLE
notify.ehmtx. Unable to find service esphome.esphomatrix_screen[BUG]

### ISSUE THREAD

**Issue by bobdivx** [lubeda/EHMTX_custom_component#1]
**Describe the bug**  
unable to call service

**To Reproduce**  
i call a service 

**Expected behavior**  
send status notification

**Screenshots**  

**Your configuration.yaml**  
```yaml
notify:
 - platform: ehmtx
   name: ehmtx32
    device: esphomatrix
    icon: alert
````
**Output of HA logs**  
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:150
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 06:24:09 (12 occurrences)
Last logged: 06:30:17

[139727114307856] Error handling message: Unable to find service esphome.esphomatrix_screen (unknown_error) from 80.11.165.78 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36)
